name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]  # выбираем версии Python, совместимые с вашими пакетами

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Установка системных зависимостей
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-distutils

      - name: Обновление pip
        run: |
          python -m pip install --upgrade pip

      - name: Установка зависимостей
        run: |
          pip install -r requirements.txt

      - name: Запуск тестов
        run: |
          pytest
